### ISSUE TITLE
Quantro failing when there is only one sample in a group of the factor

### ISSUE THREAD

**Issue by tiagochst** [stephaniehicks/quantro#1]
Hello,

In the case with one sample in a stage, the code does not run.
<img width="771" alt="Screen Shot 2019-08-08 at 12 32 04 PM" src="https://user-images.githubusercontent.com/145529/62716464-99727380-b9d8-11e9-9bc0-39a9931b8668.png">

<img width="252" alt="Screen Shot 2019-08-08 at 12 31 56 PM" src="https://user-images.githubusercontent.com/145529/62716466-9a0b0a00-b9d8-11e9-9458-c5ad1e164adc.png">

I believe that, if you set drop = FALSE ( `rowMeans(Fnik[, which(groupFactor %in% x), drop = FALSE])`) at 
https://github.com/stephaniehicks/quantro/blob/master/R/AllClasses.R#L212, I believe it should work.

**Comment by stephaniehicks** [comment]
Hi @tiagochst, 

Thanks! See fix here: https://github.com/stephaniehicks/quantro/commit/75d6a6eb7ccbeb18c80555679b80650635c8ef88

All the best, 
Stephanie

**Comment by tiagochst** [comment]
@stephaniehicks I am still getting the problem. Probably at line https://github.com/stephaniehicks/quantro/blob/master/R/AllClasses.R#L222

**Comment by tiagochst** [comment]
Here is a small example how to replicate the problem.
```
library(minfi)
data(flowSorted)
p <- getBeta(flowSorted, offset = 100)
pd <- pData(flowSorted)
pd$CellType[1] <- "test"
qtest <- quantro(object = p, groupFactor = pd$CellType)
```

**Comment by stephaniehicks** [comment]
Hi @tiagochst, 

Thanks for following up on this. I've fixed it here: https://github.com/stephaniehicks/quantro/commit/4035e4f75dabb967635d7e2a6786d4ff699fb834

All the best, 
Stephanie
