### ISSUE TITLE
Quantro failing when there is only one sample in a group of the factor

### ISSUE THREAD

**Issue by tiagochst** [stephaniehicks/quantro#2]
Hello,

when the group factor has only one sample, the code does not run.
Here is a small example of how to replicate the problem.

```
library(minfi)
data(flowSorted)
p <- getBeta(flowSorted, offset = 100)
pd <- pData(flowSorted)
pd$CellType[1] <- "test"
qtest <- quantro(object = p, groupFactor = pd$CellType)
```

**Comment by stephaniehicks** [comment]
Thanks @tiagochst. 

Fixed here: https://github.com/stephaniehicks/quantro/commit/4035e4f75dabb967635d7e2a6786d4ff699fb834

All the best, 
Stephanie

**Comment by stephaniehicks** [comment]
Closing this issue.
